// M.s

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ignore: avoid_classes_with_only_static_members
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_Co.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "add ur key here",
    authDomain: "add ur key here",
    projectId: "add ur key here",
    storageBucket: "add ur key here",
    messagingSenderId: "add ur key here",
    appId: "add ur key here",
    measurementId: "add ur key here",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "add ur key here",
    authDomain: "add ur key here",
    projectId: "add ur key here",
    storageBucket: "add ur key here",
    messagingSenderId: "add ur key here",
    appId: "add ur key here",
    measurementId: "add ur key here",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "add ur key here",
    authDomain: "add ur key here",
    projectId: "add ur key here",
    storageBucket: "add ur key here",
    messagingSenderId: "add ur key here",
    appId: "add ur key here",
    measurementId: "add ur key here",
    androidClientId:
    "add ur key here",
    iosClientId:
    "add ur key here",
    iosBundleId: 'io.github',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "add ur key here",
    authDomain: "add ur key here",
    projectId: "add ur key here",
    storageBucket: "add ur key here",
    messagingSenderId: "add ur key here",
    appId: "add ur key here",
    measurementId: "add ur key here",
    androidClientId:
    "add ur key here",
    iosClientId:
    "add ur key here",
    iosBundleId: 'io.github',
  );
}